{% set name = "versioneer" %}
{% set version = "0.29" %}
{% set sha256 = "5ab283b9857211d61b53318b7c792cf68e798e765ee17c27ade9f6c924235731" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - versioneer = versioneer:main

requirements:
  host:
    - pip
    - python >=3.7
    - setuptools
    - tomli
  run:
    - python >=3.7

test:
  requires:
    - pip
  commands:
    - pip check
    - versioneer version

about:
  home: https://github.com/python-versioneer/python-versioneer
  license: Unlicense
  license_file: LICENSE
  summary: Easy VCS-based management of project version strings

extra:
  recipe-maintainers:
    - jakirkham
